# argument to provide specific version of fury node
ARG INITIAL_VERSION
FROM tharsishq/fury:$INITIAL_VERSION

WORKDIR /go/src/github.com/exfury/fury

COPY ./init-node.sh .

# JSON-RPC server
EXPOSE 8545

CMD ["sh", "./init-node.sh"]
